const KEYS={overrides:'camping-map-overrides-v1',userSites:'camping-map-user-sites-v1'};
const CATS={'Boondocking':'#b26a1b','State, County & Town Campgrounds':'#2d6f96','Federal Lands':'#2d8a57','Private Campgrounds':'#8657b7','Info / Reference':'#c45454'};
const state={baseSites:[],userSites:load(KEYS.userSites,[]),overrides:load(KEYS.overrides,{}),visible:new Set(Object.keys(CATS)),search:'',selected:null,moveTarget:null,addMode:false,markers:new Map()};
const $=id=>document.getElementById(id); const els={recordCount:$('recordCount'),layerFilters:$('layerFilters'),mobileChips:$('mobileChips'),searchInput:$('searchInput'),sheetContent:$('sheetContent'),siteTemplate:$('siteTemplate'),resetFiltersBtn:$('resetFiltersBtn'),addSiteBtn:$('addSiteBtn'),floatingAddBtn:$('floatingAddBtn'),exportEditsBtn:$('exportEditsBtn'),importEditsInput:$('importEditsInput'),clearEditsBtn:$('clearEditsBtn'),locateBtn:$('locateBtn'),menuBtn:$('menuBtn'),sidebar:$('sidebar')};
const map=L.map('map',{zoomControl:true,preferCanvas:true}).setView([44.8,-88.6],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);const cluster=L.markerClusterGroup({maxClusterRadius:50,showCoverageOnHover:false,iconCreateFunction(c){const n=c.getChildCount(),s=n<20?40:n<80?48:56;return L.divIcon({html:`<div style="width:${s}px;height:${s}px;border-radius:50%;background:rgba(31,81,49,.88);color:#fff;border:3px solid rgba(255,255,255,.75);display:flex;align-items:center;justify-content:center;font-weight:700">${n}</div>`,className:'',iconSize:[s,s]})}});map.addLayer(cluster);
init();
async function init(){registerSW();wire();const res=await fetch('./data/sites.json');state.baseSites=await res.json();renderChips();renderMarkers();fitVisible()}
function wire(){els.searchInput.addEventListener('input',e=>{state.search=e.target.value.trim().toLowerCase();renderMarkers()});els.resetFiltersBtn.addEventListener('click',()=>{state.visible=new Set(Object.keys(CATS));state.search='';els.searchInput.value='';renderChips();renderMarkers()});[els.addSiteBtn,els.floatingAddBtn].forEach(b=>b.addEventListener('click',toggleAdd));els.exportEditsBtn.addEventListener('click',exportEdits);els.importEditsInput.addEventListener('change',importEdits);els.clearEditsBtn.addEventListener('click',clearEdits);els.locateBtn.addEventListener('click',fitVisible);els.menuBtn.addEventListener('click',()=>els.sidebar.classList.toggle('open'));map.on('click',e=>{if(state.addMode)addSiteAt(e.latlng);else if(state.moveTarget)moveSiteTo(state.moveTarget,e.latlng)})}
function merged(){const base=state.baseSites.map(s=>({...s,...(state.overrides[s.id]||{}),isUserSite:false}));return [...base,...state.userSites]}
function visibleSites(){return merged().filter(s=>state.visible.has(s.category)&&(!state.search||`${s.name} ${s.description||''} ${s.sourceLayer||''} ${s.category}`.toLowerCase().includes(state.search)))}
function renderChips(){const counts=Object.fromEntries(Object.keys(CATS).map(k=>[k,0]));merged().forEach(s=>counts[s.category]=(counts[s.category]||0)+1);[els.layerFilters,els.mobileChips].forEach(box=>{box.innerHTML='';Object.keys(CATS).forEach(cat=>{const b=document.createElement('button');b.className=`chip ${state.visible.has(cat)?'active':''}`;b.innerHTML=`<span>${cat}</span><span class="count">${counts[cat]||0}</span>`;b.onclick=()=>{state.visible.has(cat)?state.visible.delete(cat):state.visible.add(cat);renderChips();renderMarkers()};box.appendChild(b)})})}
function renderMarkers(){cluster.clearLayers();state.markers.clear();const sites=visibleSites();sites.forEach(site=>{const m=L.marker([site.lat,site.lng],{icon:L.divIcon({className:'',html:`<div class="custom-marker" style="background:${CATS[site.category]||'#355'}"></div>`,iconSize:[18,18],iconAnchor:[9,9]})});m.on('click',()=>showSite(site.id));cluster.addLayer(m);state.markers.set(site.id,m)});els.recordCount.textContent=`${sites.length} visible site${sites.length===1?'':'s'} · ${merged().length} total`;if(state.selected&&!sites.find(s=>s.id===state.selected)){state.selected=null;emptySheet()}}
function showSite(id){const site=merged().find(s=>s.id===id);if(!site)return;state.selected=id;const node=els.siteTemplate.content.firstElementChild.cloneNode(true);node.querySelector('[data-field="category"]').textContent=site.category;node.querySelector('[data-field="name"]').textContent=site.name;node.querySelector('[data-field="sourceLayer"]').textContent=site.sourceLayer||(site.isUserSite?'User-added site':'Imported site');node.querySelector('[data-field="lat"]').textContent=Number(site.lat).toFixed(6);node.querySelector('[data-field="lng"]').textContent=Number(site.lng).toFixed(6);node.querySelector('[data-field="description"]').innerHTML=site.description||'<p>No notes yet.</p>';node.querySelector('[data-action="move"]').onclick=()=>startMove(id);node.querySelector('[data-action="copy"]').onclick=async()=>{await navigator.clipboard.writeText(`${site.lat}, ${site.lng}`);toast('Coordinates copied.')};els.sheetContent.innerHTML='';els.sheetContent.appendChild(node);const m=state.markers.get(id);if(m)map.panTo(m.getLatLng(),{animate:true})}
function emptySheet(){els.sheetContent.innerHTML='<div class="empty-state"><h2>Ready to roam</h2><p>Tap a pin to see details, move it, or open its notes.</p></div>'}
function startMove(id){state.moveTarget=id;state.addMode=false;toast('Tap the new location on the map.')}
function moveSiteTo(id,latlng){const base=state.baseSites.find(s=>s.id===id);if(base){state.overrides[id]={...(state.overrides[id]||{}),lat:latlng.lat,lng:latlng.lng};save(KEYS.overrides,state.overrides)}else{const i=state.userSites.findIndex(s=>s.id===id);if(i>=0){state.userSites[i].lat=latlng.lat;state.userSites[i].lng=latlng.lng;save(KEYS.userSites,state.userSites)}}state.moveTarget=null;renderMarkers();showSite(id);toast('Site moved and saved locally.')}
function toggleAdd(){state.addMode=!state.addMode;state.moveTarget=null;toast(state.addMode?'Tap the map to add a new site.':'Add mode cancelled.')}
function addSiteAt(latlng){const name=prompt('Site name?');if(!name){state.addMode=false;return}const category=prompt(`Category?\n${Object.keys(CATS).join(' | ')}`,'Boondocking')||'Boondocking';const description=prompt('Notes / description?','')||'';const cat=Object.keys(CATS).includes(category)?category:'Boondocking';const site={id:`user-${Date.now()}`,name,lat:latlng.lat,lng:latlng.lng,description,sourceLayer:'User-added site',category:cat,isUserSite:true};state.userSites.push(site);save(KEYS.userSites,state.userSites);state.addMode=false;renderChips();renderMarkers();showSite(site.id);toast('New site added locally.')}
function fitVisible(){const sites=visibleSites();if(!sites.length)return;map.fitBounds(L.latLngBounds(sites.map(s=>[s.lat,s.lng])).pad(.08),{animate:true})}
function exportEdits(){const payload={exportedAt:new Date().toISOString(),overrides:state.overrides,userSites:state.userSites};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='camping-map-edits.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
async function importEdits(e){const file=e.target.files?.[0];if(!file)return;try{const p=JSON.parse(await file.text());state.overrides=p.overrides||{};state.userSites=p.userSites||[];save(KEYS.overrides,state.overrides);save(KEYS.userSites,state.userSites);renderChips();renderMarkers();toast('Edits imported.')}catch{toast('Could not import that file.')}e.target.value=''}
function clearEdits(){if(!confirm('Clear all locally saved moves and user-added sites in this browser?'))return;state.overrides={};state.userSites=[];save(KEYS.overrides,state.overrides);save(KEYS.userSites,state.userSites);renderChips();renderMarkers();emptySheet();toast('Local edits cleared.')}
function load(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}} function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function toast(msg){document.querySelectorAll('.toast').forEach(n=>n.remove());const n=document.createElement('div');n.className='toast';n.textContent=msg;document.body.appendChild(n);setTimeout(()=>n.remove(),1800)}
function registerSW(){if('serviceWorker' in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{})}
