window.CAMPSITE_DATA = {
  version: 'v20.4-rebuild',
  generatedOn: '2026-03-19',
  center: [-89.32, 46.43],
  zoom: 8.1,
  sites: [
    {
      name: 'Black River Harbor Campground',
      kind: 'campground',
      category: 'modern',
      owner: 'federal',
      fee: '$22/night',
      lat: 46.66416323,
      lng: -90.05190622,
      access: '2WD seasonal',
      notes: 'Developed Ottawa NF campground adjacent to Black River Harbor Recreation Area.',
      source: 'USFS / Recreation.gov',
      sourceUrl: 'https://www.fs.usda.gov/r09/ottawa/recreation/black-river-harbor-recreation-area'
    },
    {
      name: 'Bob Lake Campground',
      kind: 'campground',
      category: 'rustic',
      owner: 'federal',
      fee: '$22/night',
      lat: 46.66230759,
      lng: -88.91411255,
      access: '2WD seasonal',
      notes: '17-site Ottawa NF campground southeast of Ontonagon.',
      source: 'USFS',
      sourceUrl: 'https://www.fs.usda.gov/r09/ottawa/recreation/bob-lake-campground'
    },
    {
      name: 'Burned Dam Campground',
      kind: 'campground',
      category: 'boondocking',
      owner: 'federal',
      fee: 'Free',
      lat: 46.31379535,
      lng: -89.05313987,
      access: '2WD/forest road',
      notes: 'Free developed dispersed site near the Middle Branch Ontonagon River and Mex-i-mine Falls.',
      source: 'USFS',
      sourceUrl: 'https://www.fs.usda.gov/r09/ottawa/recreation/burned-dam-campground'
    },
    {
      name: 'Courtney Lake Campground',
      kind: 'campground',
      category: 'rustic',
      owner: 'federal',
      fee: '$22/night',
      lat: 46.75241443,
      lng: -88.94030846,
      access: '2WD seasonal',
      notes: '21-site Ottawa NF campground with equestrian-capable sites.',
      source: 'USFS',
      sourceUrl: 'https://www.fs.usda.gov/r09/ottawa/recreation/courtney-lake-campground'
    },
    {
      name: 'Deer Lake State Forest Campground',
      kind: 'campground',
      category: 'rustic',
      owner: 'state',
      fee: '$20/night typical',
      lat: 46.325327,
      lng: -88.324349,
      access: '2WD seasonal',
      notes: 'Michigan state forest campground with 12 sites on Deer Lake.',
      source: 'Michigan DNR',
      sourceUrl: 'https://www.michigan.gov/recsearch/sfcampgroundsa-m/deerlake'
    },
    {
      name: 'Lake Ottawa Campground',
      kind: 'campground',
      category: 'modern',
      owner: 'federal',
      fee: '$22/night',
      lat: 46.0807608,
      lng: -88.76003616,
      access: '2WD seasonal',
      notes: '32-site Ottawa NF campground with flush toilets, pressurized water, and dump station.',
      source: 'USFS / Recreation.gov',
      sourceUrl: 'https://www.fs.usda.gov/r09/ottawa/recreation/lake-ottawa-recreation-area'
    },
    {
      name: 'Norway Lake Campground',
      kind: 'campground',
      category: 'rustic',
      owner: 'federal',
      fee: '$22/night',
      lat: 46.41583408,
      lng: -88.68205671,
      access: '2WD seasonal',
      notes: '27-site Ottawa NF campground in tall red pines.',
      source: 'USFS',
      sourceUrl: 'https://www.fs.usda.gov/r09/ottawa/recreation/norway-lake-campground'
    },
    {
      name: 'Paint River Forks Campground',
      kind: 'campground',
      category: 'boondocking',
      owner: 'federal',
      fee: 'Free',
      lat: 46.23240559,
      lng: -88.71756443,
      access: '2WD/forest road',
      notes: 'Free developed site at the fork of the North and South Branch Paint River.',
      source: 'USFS',
      sourceUrl: 'https://www.fs.usda.gov/r09/ottawa/recreation/paint-river-forks-campground'
    },
    {
      name: 'Perch Lake Campground',
      kind: 'campground',
      category: 'rustic',
      owner: 'federal',
      fee: '$22/night',
      lat: 46.364325,
      lng: -88.674424,
      access: '2WD seasonal',
      notes: '20-site Ottawa NF campground south of Sidnaw with lake access.',
      source: 'USFS',
      sourceUrl: 'https://www.fs.usda.gov/r09/ottawa/recreation/perch-lake-campground'
    },
    {
      name: 'Presque Isle Campground (Porcupine Mountains)',
      kind: 'campground',
      category: 'rustic',
      owner: 'state',
      fee: 'State park rustic rates',
      lat: 46.70638,
      lng: -89.9792,
      access: '2WD seasonal',
      notes: 'Rustic Porcupine Mountains campground. Coordinates from Outdoor Michigan listing.',
      source: 'Outdoor Michigan',
      sourceUrl: 'https://outdoormichigan.org/feature/12033'
    },
    {
      name: 'Sturgeon River Campground',
      kind: 'campground',
      category: 'boondocking',
      owner: 'federal',
      fee: '$16/night',
      lat: 46.570096,
      lng: -88.65636953,
      access: '2WD/forest road',
      notes: 'Small developed-dispersed style campground next to Sturgeon River Gorge Wilderness.',
      source: 'USFS',
      sourceUrl: 'https://www.fs.usda.gov/r09/ottawa/recreation/sturgeon-river-campground'
    },
    {
      name: 'Sylvania (Clark Lake) Campground',
      kind: 'campground',
      category: 'modern',
      owner: 'federal',
      fee: '$22–$26/night',
      lat: 46.24029372,
      lng: -89.3223604,
      access: '2WD seasonal',
      notes: '48-site Ottawa NF campground adjacent to Sylvania Wilderness.',
      source: 'USFS',
      sourceUrl: 'https://www.fs.usda.gov/r09/ottawa/recreation/sylvania-clark-lake-campground'
    },
    {
      name: 'Bobcat Lake Camp',
      kind: 'campground',
      category: 'rustic',
      owner: 'federal',
      fee: 'Federal campground rate',
      lat: 46.35924,
      lng: -89.672941,
      access: '2WD seasonal',
      notes: 'Ottawa NF Bessemer Ranger District campground. Coordinates from The Dyrt listing.',
      source: 'The Dyrt',
      sourceUrl: 'https://thedyrt.com/camping/michigan/bobcat-lake-camp-ottawa-national-forest'
    },
    {
      name: 'Pomeroy Lake Camp',
      kind: 'campground',
      category: 'rustic',
      owner: 'federal',
      fee: 'Federal campground rate',
      lat: 46.281466,
      lng: -89.573968,
      access: '2WD seasonal',
      notes: 'Ottawa NF Bessemer Ranger District campground. Coordinates from The Dyrt listing.',
      source: 'The Dyrt',
      sourceUrl: 'https://thedyrt.com/camping/michigan/michigan-pomeroy-lake-campground'
    },
    {
      name: 'Marion Lake Campground / Group Site',
      kind: 'campground',
      category: 'modern',
      owner: 'federal',
      fee: '$75 group site / single-site federal rates',
      lat: 46.269137,
      lng: -89.086584,
      access: '2WD seasonal',
      notes: '37-site campground with separate reservable group site.',
      source: 'USFS',
      sourceUrl: 'https://www.fs.usda.gov/r09/ottawa/recreation/marion-lake-campground'
    }
  ],
  opportunityAreas: [
    {
      name: 'Trap Hills dispersed camping area',
      kind: 'opportunity',
      category: 'boondocking',
      owner: 'federal',
      fee: 'Free',
      lat: 46.658854,
      lng: -89.446034,
      access: 'Mixed; many non-motorized segments',
      notes: 'Official Ottawa NF dispersed camping area. Point only in this rebuild; boundary polygon intentionally omitted pending tighter parcel verification.',
      source: 'USFS',
      sourceUrl: 'https://www.fs.usda.gov/r09/ottawa/recreation/trap-hills'
    },
    {
      name: 'Sturgeon River Gorge Wilderness dispersed camping',
      kind: 'opportunity',
      category: 'boondocking',
      owner: 'federal',
      fee: 'Free',
      lat: 46.6105007,
      lng: -88.7003002,
      access: 'Hike-in / trailhead access',
      notes: 'Official dispersed camping in wilderness. Point only here; no polygon drawn until ownership-safe geometry is verified.',
      source: 'USFS + TopoZone',
      sourceUrl: 'https://www.fs.usda.gov/r09/ottawa/recreation/sturgeon-river-gorge-wilderness'
    },
    {
      name: 'Sylvania Wilderness backcountry camping',
      kind: 'opportunity',
      category: 'boondocking',
      owner: 'federal',
      fee: 'Backcountry permit rules apply',
      lat: 46.2446341,
      lng: -89.31003087,
      access: 'Trailhead / boat landing access',
      notes: 'Official Ottawa NF backcountry camping area. Point only in this rebuild.',
      source: 'USFS',
      sourceUrl: 'https://www.fs.usda.gov/r09/ottawa/recreation/sylvania-wilderness-backcountry-camping'
    }
  ]
};
